### ISSUE TITLE
Trying to access array offset on value of type bool on line 75

### ISSUE THREAD

**Issue by musicpanda** [thirtybees/sendtoafriend#2]
In my errorlog I find warnings like the following

> [Thu Dec 01 17:28:54.432014 2022] [php:warn] [pid 7404] [client 12234] PHP Warning:  Trying to access array offset on value of type bool in /sites/www.shop.com/modules/sendtoafriend/sendtoafriend.php on line 75, 

When I check the code I see the following:
![friend](https://user-images.githubusercontent.com/13930107/205280131-209d483f-2a19-4ff0-a6f7-d71c4c1e577e.jpg)

My guess is that this concerns products without an image.

**Comment by getdatakick** [comment]
Right, the image probably doesn't exists. We should fix this by conditional check.

Also, using image identifiers in format `{productId}_{imageId}` is no longer needed, and is actually deprecated. We should simply pass image id, without the product prefix.
